name: Test

on:
  push:
    branches: [ main, working-version ]
  pull_request:
    branches: [ main, working-version ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Use Node.js instead of Bun for now
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Run Tests
        run: node dist/test/test-proof-verify.js